// Self-contained seed data for the standalone Midcentury ADU project.
// Extracted from the original shared HEMMA/Midcentury monorepo database.
// Contains only rows scoped to Midcentury ADU (models, images, products) plus
// posts shared across both sites. Image URLs are relative to this project's
// own /client/public directory (no /midcentury-adu path prefix, which only
// existed in the old monorepo's multi-artifact routing).

export const seedModels = [
  {
    id: 1,
    slug: "palm",
    name: "PALM",
    sf: 400,
    type: "studio",
    badge: "STUDIO",
    badgeBg: "#E8A020",
    badgeColor: "#1A1A1A",
    scenario: "The Studio",
    tagline: "The ideal compact retreat",
    beds: "Studio",
    baths: 1,
    stories: 1,
    priceCents: 18900000,
    furnishingPriceCents: 820000,
    description: "The PALM is your ideal compact retreat — a fully realized studio with clean post-and-beam bones, floor-to-ceiling glass, and a warm cedar exterior. Purpose-built for creative work, guest hosting, or income generation. Every square foot is intentional.",
    sortOrder: 0,
    isPublished: true,
    createdAt: new Date("2026-05-02T22:11:17.282818"),
    updatedAt: new Date("2026-05-02T22:11:17.282818"),
  },
  {
    id: 2,
    slug: "grove",
    name: "GROVE",
    sf: 550,
    type: "1bd",
    badge: "1 BED",
    badgeBg: "#0057A8",
    badgeColor: "#fff",
    scenario: "The Sanctuary",
    tagline: "A private sanctuary for one",
    beds: "1",
    baths: 1,
    stories: 1,
    priceCents: 22900000,
    furnishingPriceCents: 1140000,
    description: "The GROVE is a complete, private 1-bedroom home — not a spare bedroom in a box. Generous glazing, a covered porch, and thoughtful material selection make it feel like a proper house at half the footprint. A dignified space for parents, guests, or long-term tenants.",
    sortOrder: 1,
    isPublished: true,
    createdAt: new Date("2026-05-02T22:11:17.295326"),
    updatedAt: new Date("2026-05-02T22:11:17.295326"),
  },
  {
    id: 3,
    slug: "haven",
    name: "HAVEN",
    sf: 700,
    type: "1bd",
    badge: "1 BED + DEN",
    badgeBg: "#0057A8",
    badgeColor: "#fff",
    scenario: "The Launchpad",
    tagline: "Room for work and rest",
    beds: "1+Den",
    baths: 1,
    stories: 1,
    priceCents: 28900000,
    furnishingPriceCents: 1480000,
    description: "The HAVEN delivers a 1-bedroom plus a dedicated den — the layout that finally lets the home office be a real room. Clerestory windows bring California light deep into the plan, while sliding glass doors open the living area onto a private patio.",
    sortOrder: 2,
    isPublished: true,
    createdAt: new Date("2026-05-02T22:11:17.303442"),
    updatedAt: new Date("2026-05-02T22:11:17.303442"),
  },
  {
    id: 4,
    slug: "mesa",
    name: "MESA",
    sf: 700,
    type: "2bd",
    badge: "2 BED",
    badgeBg: "#0057A8",
    badgeColor: "#fff",
    scenario: "The Dividend",
    tagline: "Classic California ranch living",
    beds: "2",
    baths: 1,
    stories: 1,
    priceCents: 25900000,
    furnishingPriceCents: 1320000,
    description: "The MESA is a clean, efficient 2-bedroom ranch at 700 sq ft — the right plan for multigenerational living or a two-room rental. Low-pitched roof, cedar siding, and two separate sleeping rooms with a shared living space and kitchen.",
    sortOrder: 3,
    isPublished: true,
    createdAt: new Date("2026-05-02T22:11:17.313202"),
    updatedAt: new Date("2026-05-02T22:11:17.313202"),
  },
  {
    id: 5,
    slug: "canyon",
    name: "CANYON",
    sf: 900,
    type: "2bd",
    badge: "2 BED · 2 BATH",
    badgeBg: "#1A1A1A",
    badgeColor: "#E8A020",
    scenario: "The Dividend",
    tagline: "Space without compromise",
    beds: "2",
    baths: 2,
    stories: 1,
    priceCents: 36900000,
    furnishingPriceCents: 1960000,
    description: "The CANYON is where midcentury modern really opens up. Two bedrooms, two full baths, 900 sq ft — with a wide glazed front elevation and deep covered overhang that creates a seamless indoor-outdoor living zone. The plan that earns the most on the rental market.",
    sortOrder: 4,
    isPublished: true,
    createdAt: new Date("2026-05-02T22:11:17.321756"),
    updatedAt: new Date("2026-05-02T22:11:17.321756"),
  },
  {
    id: 6,
    slug: "loft",
    name: "LOFT",
    sf: 1100,
    type: "carriage",
    badge: "CARRIAGE",
    badgeBg: "#8B7355",
    badgeColor: "#fff",
    scenario: "The Sanctuary",
    tagline: "Elevated living above the garage",
    beds: "1",
    baths: 1,
    stories: 2,
    priceCents: 42900000,
    furnishingPriceCents: 2240000,
    description: "The LOFT is a carriage house — living quarters above the garage, with vertical cedar cladding and industrial-framed windows that make it read as architecture rather than an addition. Perfect for properties with existing garages or alley access.",
    sortOrder: 5,
    isPublished: true,
    createdAt: new Date("2026-05-02T22:11:17.332372"),
    updatedAt: new Date("2026-05-02T22:11:17.332372"),
  },
  {
    id: 7,
    slug: "ranch",
    name: "RANCH",
    sf: 1100,
    type: "3bd",
    badge: "3 BED",
    badgeBg: "#2D6A2D",
    badgeColor: "#fff",
    scenario: "The Family",
    tagline: "The full midcentury family plan",
    beds: "3",
    baths: 2,
    stories: 1,
    priceCents: 41900000,
    furnishingPriceCents: 2480000,
    description: "The RANCH is the full California family plan — three bedrooms, two baths, 1,100 sq ft of single-story midcentury living with a wide covered terrace. The layout that accommodates a growing family while keeping the post-and-beam character that makes it a home.",
    sortOrder: 6,
    isPublished: true,
    createdAt: new Date("2026-05-02T22:11:17.340269"),
    updatedAt: new Date("2026-05-02T22:11:17.340269"),
  },
  {
    id: 8,
    slug: "ridge",
    name: "RIDGE",
    sf: 1200,
    type: "2story",
    badge: "2-STORY",
    badgeBg: "#1A1A1A",
    badgeColor: "#E8A020",
    scenario: "The Legacy",
    tagline: "Dramatic two-level presence",
    beds: "1",
    baths: 2,
    stories: 2,
    priceCents: 46900000,
    furnishingPriceCents: 2680000,
    description: "The HÖJD is HEMMA's most architecturally ambitious model — a two-story structure with dramatic ceiling heights, a main-floor living suite, and an upper loft with soaking tub en-suite and private balcony. Built for the homeowner who wants a landmark, not just an income property.",
    sortOrder: 7,
    isPublished: true,
    createdAt: new Date("2026-05-02T22:11:17.348723"),
    updatedAt: new Date("2026-05-02T22:11:17.348723"),
  }
] as const;

export const seedModelImages = [
  {
    id: 9,
    modelId: 1,
    url: "/elevations/palm.png",
    alt: "PALM exterior elevation",
    kind: "hero",
    sortOrder: -1,
    createdAt: new Date("2026-05-02T22:44:35.250978"),
  },
  {
    id: 10,
    modelId: 2,
    url: "/elevations/grove.png",
    alt: "GROVE exterior elevation",
    kind: "hero",
    sortOrder: -1,
    createdAt: new Date("2026-05-02T22:44:35.250978"),
  },
  {
    id: 11,
    modelId: 3,
    url: "/elevations/haven.png",
    alt: "HAVEN exterior elevation",
    kind: "hero",
    sortOrder: -1,
    createdAt: new Date("2026-05-02T22:44:35.250978"),
  },
  {
    id: 12,
    modelId: 4,
    url: "/elevations/mesa.png",
    alt: "MESA exterior elevation",
    kind: "hero",
    sortOrder: -1,
    createdAt: new Date("2026-05-02T22:44:35.250978"),
  },
  {
    id: 13,
    modelId: 5,
    url: "/elevations/canyon.png",
    alt: "CANYON exterior elevation",
    kind: "hero",
    sortOrder: -1,
    createdAt: new Date("2026-05-02T22:44:35.250978"),
  },
  {
    id: 14,
    modelId: 6,
    url: "/elevations/loft.png",
    alt: "LOFT exterior elevation",
    kind: "hero",
    sortOrder: -1,
    createdAt: new Date("2026-05-02T22:44:35.250978"),
  },
  {
    id: 15,
    modelId: 7,
    url: "/elevations/ranch.png",
    alt: "RANCH exterior elevation",
    kind: "hero",
    sortOrder: -1,
    createdAt: new Date("2026-05-02T22:44:35.250978"),
  },
  {
    id: 16,
    modelId: 8,
    url: "/elevations/ridge.png",
    alt: "RIDGE exterior elevation",
    kind: "hero",
    sortOrder: -1,
    createdAt: new Date("2026-05-02T22:44:35.250978"),
  },
  {
    id: 6,
    modelId: 1,
    url: "/floorplans/palm.svg",
    alt: "KOJA floor plan (placeholder)",
    kind: "floorplan",
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:42:46.850005"),
  },
  {
    id: 1,
    modelId: 2,
    url: "/floorplans/grove.svg",
    alt: "FRISTAD floor plan (placeholder)",
    kind: "floorplan",
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:42:46.850005"),
  },
  {
    id: 7,
    modelId: 3,
    url: "/floorplans/haven.svg",
    alt: "SPRÅNG floor plan (placeholder)",
    kind: "floorplan",
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:42:46.850005"),
  },
  {
    id: 5,
    modelId: 4,
    url: "/floorplans/mesa.svg",
    alt: "TORP floor plan (placeholder)",
    kind: "floorplan",
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:42:46.850005"),
  },
  {
    id: 2,
    modelId: 5,
    url: "/floorplans/canyon.svg",
    alt: "AVKAST floor plan (placeholder)",
    kind: "floorplan",
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:42:46.850005"),
  },
  {
    id: 4,
    modelId: 6,
    url: "/floorplans/loft.svg",
    alt: "LOGE floor plan (placeholder)",
    kind: "floorplan",
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:42:46.850005"),
  },
  {
    id: 8,
    modelId: 7,
    url: "/floorplans/ranch.svg",
    alt: "GÅRD floor plan (placeholder)",
    kind: "floorplan",
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:42:46.850005"),
  },
  {
    id: 3,
    modelId: 8,
    url: "/floorplans/ridge.svg",
    alt: "HÖJD floor plan (placeholder)",
    kind: "floorplan",
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:42:46.850005"),
  }
] as const;

export const seedIncludedProducts = [
  {
    id: 13,
    modelId: 3,
    name: "MALM Queen Bed + Storage",
    url: "https://www.ikea.com/us/en/cat/malm-series-07468/",
    category: null,
    sortOrder: 0,
    createdAt: new Date("2026-05-02T22:11:17.308367"),
  },
  {
    id: 7,
    modelId: 2,
    name: "HEMNES Queen Bed + 2 Nightstands",
    url: "https://www.ikea.com/us/en/p/hemnes-bed-frame-white-stain-luroey-s99007856/",
    category: null,
    sortOrder: 0,
    createdAt: new Date("2026-05-02T22:11:17.299373"),
  },
  {
    id: 1,
    modelId: 1,
    name: "SÄNG HEMNES Bed Frame",
    url: "https://www.ikea.com/us/en/p/hemnes-bed-frame-white-stain-luroey-s99007856/",
    category: null,
    sortOrder: 0,
    createdAt: new Date("2026-05-02T22:11:17.289201"),
  },
  {
    id: 19,
    modelId: 4,
    name: "2× HEMNES Full Beds + Frames",
    url: "https://www.ikea.com/us/en/p/hemnes-bed-frame-white-stain-s69931575/",
    category: null,
    sortOrder: 0,
    createdAt: new Date("2026-05-02T22:11:17.317029"),
  },
  {
    id: 25,
    modelId: 5,
    name: "NORDLI King Bed + Nightstands",
    url: "https://www.ikea.com/us/en/p/nordli-bed-with-headboard-and-storage-anthracite-s39241409/",
    category: null,
    sortOrder: 0,
    createdAt: new Date("2026-05-02T22:11:17.325631"),
  },
  {
    id: 31,
    modelId: 6,
    name: "NORDLI King Bed + Nightstands",
    url: "https://www.ikea.com/us/en/p/nordli-bed-with-headboard-and-storage-anthracite-s39241409/",
    category: null,
    sortOrder: 0,
    createdAt: new Date("2026-05-02T22:11:17.336265"),
  },
  {
    id: 37,
    modelId: 7,
    name: "NORDLI King Bed + WIC System",
    url: "https://www.ikea.com/us/en/p/nordli-bed-with-headboard-and-storage-anthracite-s39241409/",
    category: null,
    sortOrder: 0,
    createdAt: new Date("2026-05-02T22:11:17.344563"),
  },
  {
    id: 43,
    modelId: 8,
    name: "NORDLI King Platform Bed",
    url: "https://www.ikea.com/us/en/p/nordli-bed-with-headboard-and-storage-anthracite-s39241409/",
    category: null,
    sortOrder: 0,
    createdAt: new Date("2026-05-02T22:11:17.35206"),
  },
  {
    id: 20,
    modelId: 4,
    name: "2× MALM 4-Drawer Dressers",
    url: "https://www.ikea.com/us/en/cat/malm-series-07468/",
    category: null,
    sortOrder: 1,
    createdAt: new Date("2026-05-02T22:11:17.317029"),
  },
  {
    id: 44,
    modelId: 8,
    name: "PAX Walk-In Wardrobe System",
    url: "https://www.ikea.com/us/en/p/pax-wardrobe-combination-white-s59560725/",
    category: null,
    sortOrder: 1,
    createdAt: new Date("2026-05-02T22:11:17.35206"),
  },
  {
    id: 2,
    modelId: 1,
    name: "RÅVAROR Small-Space Sofa",
    url: "https://www.ikea.com/us/en/search/?q=ravaror",
    category: null,
    sortOrder: 1,
    createdAt: new Date("2026-05-02T22:11:17.289201"),
  },
  {
    id: 38,
    modelId: 7,
    name: "2× HEMNES Full Beds",
    url: "https://www.ikea.com/us/en/p/hemnes-bed-frame-white-stain-s69931575/",
    category: null,
    sortOrder: 1,
    createdAt: new Date("2026-05-02T22:11:17.344563"),
  },
  {
    id: 32,
    modelId: 6,
    name: "PAX Walk-In Wardrobe System",
    url: "https://www.ikea.com/us/en/p/pax-wardrobe-combination-white-s59560725/",
    category: null,
    sortOrder: 1,
    createdAt: new Date("2026-05-02T22:11:17.336265"),
  },
  {
    id: 14,
    modelId: 3,
    name: "MARKUS Office Chair + MICKE Desk",
    url: "https://www.ikea.com/us/en/p/markus-office-chair-vissle-dark-gray-90289172/",
    category: null,
    sortOrder: 1,
    createdAt: new Date("2026-05-02T22:11:17.308367"),
  },
  {
    id: 8,
    modelId: 2,
    name: "BESTÅ Living Room System",
    url: "https://www.ikea.com/us/en/cat/besta-series-00785/",
    category: null,
    sortOrder: 1,
    createdAt: new Date("2026-05-02T22:11:17.299373"),
  },
  {
    id: 26,
    modelId: 5,
    name: "SÖDERHAMN Living Room Set",
    url: "https://www.ikea.com/us/en/cat/soederhamn-series-22178/",
    category: null,
    sortOrder: 1,
    createdAt: new Date("2026-05-02T22:11:17.325631"),
  },
  {
    id: 9,
    modelId: 2,
    name: "METOD Kitchen Cabinetry",
    url: "https://www.ikea.com/us/en/cat/metod-system-smet/",
    category: null,
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:11:17.299373"),
  },
  {
    id: 15,
    modelId: 3,
    name: "BILLY Bookcase System",
    url: "https://www.ikea.com/us/en/cat/billy-bookcases-58288/",
    category: null,
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:11:17.308367"),
  },
  {
    id: 21,
    modelId: 4,
    name: "METOD Kitchen Cabinetry",
    url: "https://www.ikea.com/us/en/cat/metod-system-smet/",
    category: null,
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:11:17.317029"),
  },
  {
    id: 45,
    modelId: 8,
    name: "METOD Kitchen + Island",
    url: "https://www.ikea.com/us/en/cat/metod-system-smet/",
    category: null,
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:11:17.35206"),
  },
  {
    id: 27,
    modelId: 5,
    name: "METOD Kitchen + Island",
    url: "https://www.ikea.com/us/en/cat/metod-system-smet/",
    category: null,
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:11:17.325631"),
  },
  {
    id: 33,
    modelId: 6,
    name: "METOD Kitchen + Island",
    url: "https://www.ikea.com/us/en/cat/metod-system-smet/",
    category: null,
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:11:17.336265"),
  },
  {
    id: 39,
    modelId: 7,
    name: "METOD Full Kitchen",
    url: "https://www.ikea.com/us/en/cat/metod-system-smet/",
    category: null,
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:11:17.344563"),
  },
  {
    id: 3,
    modelId: 1,
    name: "KNOXHULT Mini Kitchen",
    url: "https://www.ikea.com/us/en/cat/knoxhult-series-49198/",
    category: null,
    sortOrder: 2,
    createdAt: new Date("2026-05-02T22:11:17.289201"),
  },
  {
    id: 40,
    modelId: 7,
    name: "STORNÄS Dining Table (6p)",
    url: "https://www.ikea.com/us/en/search/?q=stornas+dining+table",
    category: null,
    sortOrder: 3,
    createdAt: new Date("2026-05-02T22:11:17.344563"),
  },
  {
    id: 34,
    modelId: 6,
    name: "SÖDERHAMN Sofa + Ottoman",
    url: "https://www.ikea.com/us/en/cat/soederhamn-series-22178/",
    category: null,
    sortOrder: 3,
    createdAt: new Date("2026-05-02T22:11:17.336265"),
  },
  {
    id: 28,
    modelId: 5,
    name: "STORNÄS Dining Table (6p)",
    url: "https://www.ikea.com/us/en/search/?q=stornas+dining+table",
    category: null,
    sortOrder: 3,
    createdAt: new Date("2026-05-02T22:11:17.325631"),
  },
  {
    id: 4,
    modelId: 1,
    name: "LISABO Dining Table (2p)",
    url: "https://www.ikea.com/us/en/cat/lisabo-series-39434/",
    category: null,
    sortOrder: 3,
    createdAt: new Date("2026-05-02T22:11:17.289201"),
  },
  {
    id: 16,
    modelId: 3,
    name: "METOD Full Kitchen",
    url: "https://www.ikea.com/us/en/cat/metod-system-smet/",
    category: null,
    sortOrder: 3,
    createdAt: new Date("2026-05-02T22:11:17.308367"),
  },
  {
    id: 22,
    modelId: 4,
    name: "EKEDALEN Dining Set (4p)",
    url: "https://www.ikea.com/us/en/cat/ekedalen-series-38609/",
    category: null,
    sortOrder: 3,
    createdAt: new Date("2026-05-02T22:11:17.317029"),
  },
  {
    id: 46,
    modelId: 8,
    name: "SÖDERHAMN Sofa + Chaise",
    url: "https://www.ikea.com/us/en/cat/soederhamn-series-22178/",
    category: null,
    sortOrder: 3,
    createdAt: new Date("2026-05-02T22:11:17.35206"),
  },
  {
    id: 10,
    modelId: 2,
    name: "EKEDALEN Dining Set (4p)",
    url: "https://www.ikea.com/us/en/cat/ekedalen-series-38609/",
    category: null,
    sortOrder: 3,
    createdAt: new Date("2026-05-02T22:11:17.299373"),
  },
  {
    id: 47,
    modelId: 8,
    name: "STORNÄS Dining (6p) + BESTÅ",
    url: "https://www.ikea.com/us/en/search/?q=stornas+dining+table",
    category: null,
    sortOrder: 4,
    createdAt: new Date("2026-05-02T22:11:17.35206"),
  },
  {
    id: 5,
    modelId: 1,
    name: "NORDLI 4-Drawer Chest",
    url: "https://www.ikea.com/us/en/cat/nordli-series-36765/",
    category: null,
    sortOrder: 4,
    createdAt: new Date("2026-05-02T22:11:17.289201"),
  },
  {
    id: 29,
    modelId: 5,
    name: "2× PAX Wardrobe Systems",
    url: "https://www.ikea.com/us/en/p/pax-wardrobe-combination-white-s59560725/",
    category: null,
    sortOrder: 4,
    createdAt: new Date("2026-05-02T22:11:17.325631"),
  },
  {
    id: 35,
    modelId: 6,
    name: "BESTÅ Media + Display System",
    url: "https://www.ikea.com/us/en/cat/besta-series-00785/",
    category: null,
    sortOrder: 4,
    createdAt: new Date("2026-05-02T22:11:17.336265"),
  },
  {
    id: 41,
    modelId: 7,
    name: "KIVIK Sofa + KALLAX Wall System",
    url: "https://www.ikea.com/us/en/cat/kivik-series-22155/",
    category: null,
    sortOrder: 4,
    createdAt: new Date("2026-05-02T22:11:17.344563"),
  },
  {
    id: 11,
    modelId: 2,
    name: "PAX Wardrobe System",
    url: "https://www.ikea.com/us/en/p/pax-wardrobe-combination-white-s59560725/",
    category: null,
    sortOrder: 4,
    createdAt: new Date("2026-05-02T22:11:17.299373"),
  },
  {
    id: 17,
    modelId: 3,
    name: "KIVIK Sofa + LACK Table",
    url: "https://www.ikea.com/us/en/cat/kivik-series-22155/",
    category: null,
    sortOrder: 4,
    createdAt: new Date("2026-05-02T22:11:17.308367"),
  },
  {
    id: 23,
    modelId: 4,
    name: "FRIHETEN Sofa",
    url: "https://www.ikea.com/us/en/p/friheten-sleeper-sofa-faringe-light-gray-40551231/",
    category: null,
    sortOrder: 4,
    createdAt: new Date("2026-05-02T22:11:17.317029"),
  },
  {
    id: 48,
    modelId: 8,
    name: "KALLAX Room Divider + BRIMNES Daybed",
    url: "https://www.ikea.com/us/en/p/kallax-shelf-unit-white-20301554/",
    category: null,
    sortOrder: 5,
    createdAt: new Date("2026-05-02T22:11:17.35206"),
  },
  {
    id: 30,
    modelId: 5,
    name: "HEMNES Bed 2 + KALLAX Storage",
    url: "https://www.ikea.com/us/en/p/hemnes-bed-frame-white-stain-s69931575/",
    category: null,
    sortOrder: 5,
    createdAt: new Date("2026-05-02T22:11:17.325631"),
  },
  {
    id: 18,
    modelId: 3,
    name: "KALLAX Shelving + Dining",
    url: "https://www.ikea.com/us/en/p/kallax-shelf-unit-white-20301554/",
    category: null,
    sortOrder: 5,
    createdAt: new Date("2026-05-02T22:11:17.308367"),
  },
  {
    id: 24,
    modelId: 4,
    name: "KALLAX Storage + LACK Tables",
    url: "https://www.ikea.com/us/en/p/kallax-shelf-unit-white-20301554/",
    category: null,
    sortOrder: 5,
    createdAt: new Date("2026-05-02T22:11:17.317029"),
  },
  {
    id: 36,
    modelId: 6,
    name: "STORNÄS Dining Table (4p)",
    url: "https://www.ikea.com/us/en/search/?q=stornas+dining+table",
    category: null,
    sortOrder: 5,
    createdAt: new Date("2026-05-02T22:11:17.336265"),
  },
  {
    id: 12,
    modelId: 2,
    name: "FRIHETEN Sofa",
    url: "https://www.ikea.com/us/en/p/friheten-sleeper-sofa-faringe-light-gray-40551231/",
    category: null,
    sortOrder: 5,
    createdAt: new Date("2026-05-02T22:11:17.299373"),
  },
  {
    id: 42,
    modelId: 7,
    name: "SUNDVIK Kids Bed (optional Bed 3)",
    url: "https://www.ikea.com/us/en/search/?q=sundvik+bed",
    category: null,
    sortOrder: 5,
    createdAt: new Date("2026-05-02T22:11:17.344563"),
  },
  {
    id: 6,
    modelId: 1,
    name: "KUNGSBACKA Kitchen Fronts",
    url: "https://www.ikea.com/us/en/search/?q=kungsbacka",
    category: null,
    sortOrder: 5,
    createdAt: new Date("2026-05-02T22:11:17.289201"),
  }
] as const;

export const seedPosts = [
  {
    id: 1,
    slug: "what-is-an-adu-california-2026",
    title: "What is an ADU? A plain-English primer for California homeowners.",
    excerpt: "An accessory dwelling unit is a smaller, independent home on the same lot as your primary house. Here's how California treats them — and why 2026 is the easiest year ever to add one.",
    body: "An **accessory dwelling unit** — ADU for short — is a complete, independent home on the same parcel as a primary residence. It has its own kitchen, bathroom, sleeping area, and entrance. In California, ADUs come in three flavors: detached (a freestanding structure in the backyard), attached (added to your existing home), and converted (a garage or basement transformed into living space).\n\n  ## Why California is leading\n\n  Since 2020, the state has passed a string of laws stripping away the local barriers that used to make ADUs nearly impossible to build. Cities can no longer require owner-occupancy, demand replacement parking in most cases, or impose minimum lot sizes. The result: a homeowner with a typical suburban lot can now add a 1,200 sq ft second home where ten years ago they couldn't even get a permit returned.\n\n  ## What HEMMA does differently\n\n  Most ADU companies sell you a structure and hand you a stack of decisions: which appliances, which fixtures, which contractor for the slab, who's running the gas line. HEMMA is the opposite — a complete system. The structure, the IKEA furnishings, the assembly, and the permitting support are all included in one fixed price.\n\n  ## What's next\n\n  If you're early in your ADU research, three pieces will help: our [floor plans page](/floor-plans) shows what HEMMA actually looks like; our [financing guide](/financing) walks through how most California homeowners pay for one; and our [process page](/process) lays out the typical 8 to 14 week timeline from deposit to keys.",
    category: "adu-basics",
    heroImageUrl: "/blog-images/ac3dd8c2-41e0-43fa-a578-643d33d268f6",
    isPublished: true,
    publishedAt: new Date("2026-05-03T02:50:52.96"),
    createdAt: new Date("2026-05-03T02:50:57.610269"),
    updatedAt: new Date("2026-05-03T02:50:57.610269"),
  },
  {
    id: 2,
    slug: "california-adu-financing-options-2026",
    title: "Five ways California homeowners are paying for ADUs in 2026.",
    excerpt: "From HELOCs and renovation loans to the state's CalHFA grant program — a clear-eyed comparison of the financing tools California ADU owners actually use.",
    body: "Most homeowners assume an ADU is paid for the same way as a kitchen remodel. It usually isn't. Here are the five most common financing paths we see.\n\n  ## 1. Home equity line of credit (HELOC)\n\n  The most flexible option. You draw against your existing home's equity as construction milestones hit. Rates float with prime, but you only pay interest on what you've drawn. Best for homeowners with substantial equity and a paid-down primary mortgage.\n\n  ## 2. Cash-out refinance\n\n  You replace your existing mortgage with a larger one and take the difference in cash. Makes sense when your current rate is already higher than today's market — otherwise you're trading a good rate for a worse one to fund a project.\n\n  ## 3. Renovation loan (FHA 203k or Fannie Mae HomeStyle)\n\n  Lets you borrow against the **future** appraised value of your home with the ADU complete. Powerful for homeowners with limited current equity, but the paperwork and inspection requirements are heavier than a HELOC.\n\n  ## 4. CalHFA ADU Grant\n\n  The California Housing Finance Agency offers grants up to **$40,000** toward predevelopment costs (architectural, engineering, permitting). It's first-come, first-served and the program pauses periodically when funds are exhausted — worth checking before you start.\n\n  ## 5. Construction-to-permanent loan\n\n  A single loan that covers construction, then converts to a standard mortgage when the ADU is complete. Cleaner than juggling a construction loan and a refinance, but lender selection matters — not every bank in California offers them.\n\n  > A quick rule of thumb: if you have meaningful equity, a HELOC is almost always the simplest. If you don't, a renovation loan or CalHFA grant is the path most of our customers take.\n\n  We're not lenders, but we work with several California-licensed brokers who specialize in ADU financing. Reach out from our [financing page](/financing) and we'll connect you.",
    category: "financing-permits",
    heroImageUrl: "/blog-images/d0e4e038-0576-4950-8ceb-87185baf0ff7",
    isPublished: true,
    publishedAt: new Date("2026-05-02T02:50:52.96"),
    createdAt: new Date("2026-05-03T02:50:57.610269"),
    updatedAt: new Date("2026-05-03T02:50:57.610269"),
  },
  {
    id: 3,
    slug: "post-and-beam-construction",
    title: "The case for post-and-beam: why Midcentury ADU builds the way it does.",
    excerpt: "We could have built conventional stick-frame ADUs. We chose post-and-beam instead. Here's the reasoning.",
    body: "When we tell people that Midcentury ADU builds with a post-and-beam structural system rather than conventional stick frame, the response is usually: *does that cost more?*\n\n  Yes. A little. Here's why we think it's worth it.\n\n  ## What stick frame does well\n\n  Stick frame is fast, code-familiar, and the default for a reason. Most residential contractors can build it, most inspectors have reviewed it, and most lumber yards stock everything you need. For a basic ADU box, it works fine.\n\n  ## What post-and-beam does better\n\n  Three things matter in a small structure: **structural honesty**, **spatial generosity**, and **connection to the outdoors**.\n\n  Post-and-beam delivers all three.\n\n  1. **Structural honesty.** The beams you see in the ceiling are real. They're holding the roof. Nothing is decorative, and nothing is hidden. That's a midcentury principle, not a style choice.\n\n  2. **Spatial generosity.** Removing interior load-bearing walls means the floor plan can breathe. You get cleaner open-plan living in a smaller footprint — something stick frame's grid of bearing points makes harder.\n\n  3. **Connection to outdoors.** Post-and-beam structures naturally accommodate larger glazing spans without complex headers. More glass, more light, less sense of enclosure.\n\n  ## The ceiling moment\n\n  Every Midcentury ADU customer mentions the same thing: *the ceiling feels higher than it actually is.*\n\n  It does. Exposed beams draw your eye up and give the vertical space a clear hierarchy. The room reads as larger than its square footage.\n\n  > This is not an accident. Mid-century architects figured this out in Pasadena and Palm Springs in the 1950s. We borrowed it wholesale, because it works.\n\n  ## The real answer to \"does it cost more?\"\n\n  Building in post-and-beam adds a modest premium to structural framing. It subtracts cost elsewhere — in drywall (exposed beams replace ceiling finishes), in complexity (fewer hidden transitions), and in the long-term repairs that come from finishes that don't match the bones beneath them.\n\n  We think the math works. But mostly, we think the spaces are better.",
    category: "inside-midcentury-adu",
    heroImageUrl: "/blog-images/b1a511c0-0a3c-4987-ba65-d7ca6202cf96",
    isPublished: true,
    publishedAt: new Date("2026-05-01T02:50:52.961"),
    createdAt: new Date("2026-05-03T02:50:57.610269"),
    updatedAt: new Date("2026-05-05T20:57:46.870739"),
  },
  {
    id: 5,
    slug: "detached-vs-attached-vs-conversion-adus",
    title: "Detached, attached, or conversion? Picking the right ADU type for your lot.",
    excerpt: "The three ADU types California recognizes, what each one actually feels like to live in, and how to pick the right one for your property.",
    body: "California recognizes three distinct ADU types, and the choice between them shapes everything that follows — cost, timeline, the experience of living in (or next to) the unit.\n\n  ## Detached ADU\n\n  A standalone structure in your backyard with its own walls, roof, and entrance. The most common HEMMA install. Best for: lots with usable backyard space, owners who want maximum privacy between units, multi-generational living.\n\n  ## Attached ADU\n\n  An addition that shares at least one wall with the primary house. Good for: lots without room for a freestanding structure, homeowners who want easier wiring/plumbing runs from the main panel.\n\n  ## Garage or basement conversion\n\n  You take existing enclosed space and convert it into a livable unit. Cheapest path *if* the existing structure is sound — but renovation surprises (foundations, ceiling height, drainage) can erase the savings.\n\n  > Our usual recommendation: if you have backyard space, go detached. The privacy is worth it, the install is faster, and resale value is highest.\n\n  If you're not sure which fits your lot, [book a discovery call](/process) — we can usually tell from a few photos.",
    category: "adu-basics",
    heroImageUrl: "/blog-images/ac3dd8c2-41e0-43fa-a578-643d33d268f6",
    isPublished: true,
    publishedAt: new Date("2026-04-29T02:50:52.961"),
    createdAt: new Date("2026-05-03T03:11:43.494401"),
    updatedAt: new Date("2026-05-03T03:11:43.494401"),
  },
  {
    id: 6,
    slug: "how-big-can-my-adu-be-california",
    title: "How big can my ADU be? California's size rules in plain English.",
    excerpt: "State law sets generous floors that local cities can't undercut. Here's what you're actually entitled to build.",
    body: "Most homeowners assume their city decides how big their ADU can be. State law has reshaped that.\n\n  ## What the state guarantees\n\n  Under current California law, every single-family lot is entitled to at least one ADU of **up to 1,200 sq ft** (detached) or 50% of the primary home's size, whichever is greater. Cities cannot impose lower size caps. Period.\n\n  ## What about height?\n\n  State law guarantees a minimum height allowance of **16 to 18 feet**, depending on whether your lot is near transit. Local cities can permit taller; they cannot require shorter for ADUs in this class.\n\n  ## Setbacks\n\n  Your ADU only needs to sit **4 feet** from the rear and side property lines. The historical 10–20 ft suburban setbacks no longer apply to compliant ADUs.\n\n  ## Why this matters\n\n  Older \"ADU-friendly\" cities used to advertise 800 sq ft caps as if they were generous. Today every California homeowner has access to a real, family-sized footprint. HEMMA's floor plans are designed within these limits — we don't have to ask for variances.",
    category: "adu-basics",
    heroImageUrl: "/blog-images/d0e4e038-0576-4950-8ceb-87185baf0ff7",
    isPublished: true,
    publishedAt: new Date("2026-04-28T02:50:52.961"),
    createdAt: new Date("2026-05-03T03:11:43.494401"),
    updatedAt: new Date("2026-05-03T03:11:43.494401"),
  },
  {
    id: 7,
    slug: "what-the-permit-process-actually-looks-like",
    title: "What the ADU permit process actually looks like in 2026.",
    excerpt: "A week-by-week walkthrough of the permitting timeline so you know what to expect and where the real waits happen.",
    body: "Permitting is the part most homeowners dread, and most of that dread is outdated. Here's what the process actually looks like for a typical California ADU today.\n\n  ## Week 0–2: Pre-application\n\n  Site survey, soil report (if needed), and architectural drawings finalized. HEMMA handles all of this for you.\n\n  ## Week 2–6: Plan check\n\n  Your local building department reviews the drawings. State law requires most cities to respond within **60 days** for compliant ADU plans. If they request changes, our drafting team revises and resubmits — usually a 1–2 week turnaround.\n\n  ## Week 6–10: Permit issuance\n\n  Approved plans get stamped. Site work (foundation, utility trenching) can begin immediately.\n\n  ## What can slow it down\n\n  - Complex utility connections (running new sewer to the back of a deep lot)\n  - Historic district overlays\n  - Coastal Commission jurisdiction (specific addresses only)\n  - A backlog at the local building department (mostly resolved post-2023 reforms)\n\n  > The headline number we share with customers: 8–14 weeks from deposit to keys, including permits. The faster end is realistic in most California suburbs today.",
    category: "financing-permits",
    heroImageUrl: "/blog-images/b1a511c0-0a3c-4987-ba65-d7ca6202cf96",
    isPublished: true,
    publishedAt: new Date("2026-04-27T02:50:52.961"),
    createdAt: new Date("2026-05-03T03:11:43.494401"),
    updatedAt: new Date("2026-05-03T03:11:43.494401"),
  },
  {
    id: 8,
    slug: "what-an-adu-actually-costs-2026",
    title: "What does an ADU actually cost in California right now?",
    excerpt: "All-in pricing for a HEMMA, including what's bundled, what's site-specific, and what most other ADU companies leave out of their advertised numbers.",
    body: "When you see \"$150K ADU!\" in an ad, you should ask: what's actually in that number?\n\n  ## What's typically bundled\n\n  The structure itself, basic delivery, and standard fixtures. Sometimes.\n\n  ## What's usually *not* in the headline price\n\n  - Foundation and site preparation (often $20–40K)\n  - Utility connections (sewer, water, gas, electrical)\n  - Permit fees and impact fees ($5–25K depending on city)\n  - Furnishings (almost never included)\n  - Final assembly labor\n\n  ## How HEMMA prices\n\n  We publish a single all-in number that includes the structure, the IKEA furnishing package, the foundation, the assembly labor, and permit support. The only line-items that vary by site are utility connections (because they depend on how far your panels and sewer line are from the install location) and city-specific permit fees.\n\n  > A typical Boden install in Southern California is around $235K all-in. A studio is closer to $185K. Get a real estimate for your address from our [Get Started](/get-started) flow.",
    category: "financing-permits",
    heroImageUrl: "/blog-images/6c2408a0-0235-4f02-ba69-ffd7cc0026dc",
    isPublished: true,
    publishedAt: new Date("2026-04-26T02:50:52.961"),
    createdAt: new Date("2026-05-03T03:11:43.494401"),
    updatedAt: new Date("2026-05-03T03:11:43.494401"),
  },
  {
    id: 9,
    slug: "sb-9-and-sb-10-explained",
    title: "SB 9 and SB 10: what they actually let California homeowners do.",
    excerpt: "Two state laws homeowners hear about constantly, what they really change about your property rights, and how they interact with ADU rules.",
    body: "Headlines about SB 9 and SB 10 have made a lot of California homeowners think their lot is now eligible for a four-plex. The reality is narrower — and more useful — than the hype.\n\n  ## SB 9 (lot splits and duplexes)\n\n  Lets eligible single-family homeowners split their lot into two parcels and/or build up to two units per parcel. Net result: up to four units on what used to be one single-family lot. There are eligibility carve-outs for historic districts, fire-risk areas, and recently-tenanted properties.\n\n  ## SB 10\n\n  A *city-level* tool: lets cities upzone certain transit-rich parcels by ordinance, bypassing CEQA. It's not a homeowner-direct law — it just gives your city a faster path to allowing more housing on your block.\n\n  ## How this stacks with ADUs\n\n  Importantly: SB 9 lots **still get ADU rights**. So an eligible parcel could end up with two primary units *plus* one ADU per parcel. That's why some California cities are quietly seeing what amounts to gentle multi-family conversion of older neighborhoods.\n\n  > Most HEMMA customers don't need SB 9 — a single ADU on their existing lot accomplishes their goal. But if you're thinking longer-term about generational property planning, it's worth a conversation with a land-use attorney.",
    category: "regulations",
    heroImageUrl: "/blog-images/5933b7d0-fbaf-4c4a-9a8b-ee09b19d765b",
    isPublished: true,
    publishedAt: new Date("2026-04-25T02:50:52.961"),
    createdAt: new Date("2026-05-03T03:11:43.494401"),
    updatedAt: new Date("2026-05-03T03:11:43.494401"),
  },
  {
    id: 10,
    slug: "owner-occupancy-and-renting-your-adu",
    title: "Can you rent your ADU? The owner-occupancy rules, demystified.",
    excerpt: "The rules around renting your ADU have changed dramatically since 2020. Here's what you can and can't do today.",
    body: "For decades, California cities required ADU owners to live on-site — a rule that killed most ADUs as financial investments.\n\n  ## The current state of the law\n\n  Statewide, **owner-occupancy requirements are prohibited** for ADUs permitted between 2020 and 2025, and most cities have permanently dropped them going forward. Translation: you can build an ADU and rent both units, or live in the ADU and rent the main house.\n\n  ## Short-term rental rules\n\n  This is where local rules still matter. Many California cities — Santa Monica, San Diego, parts of LA — restrict or prohibit using ADUs as Airbnbs. The state did **not** preempt local STR rules.\n\n  ## What we usually recommend\n\n  Long-term rentals (12+ month leases) are protected by state law and produce more stable income. Short-term rentals can pencil out higher per-night, but face more regulatory risk and operational overhead.\n\n  > A rough rule of thumb in LA-area suburbs: a HEMMA Boden rents long-term for $2,400–3,400/month depending on neighborhood. That's enough to cover the financing for most homeowners.",
    category: "regulations",
    heroImageUrl: "/blog-images/6fffa802-c0c3-4862-b0a9-491715b4d30c",
    isPublished: true,
    publishedAt: new Date("2026-04-24T02:50:52.961"),
    createdAt: new Date("2026-05-03T03:11:43.494401"),
    updatedAt: new Date("2026-05-03T03:11:43.494401"),
  },
  {
    id: 11,
    slug: "what-counts-as-a-junior-adu",
    title: "JADUs vs ADUs: what's a Junior ADU and when does it make sense?",
    excerpt: "A Junior ADU is a smaller, cheaper-to-permit category with its own rules. Here's when one beats a full ADU.",
    body: "Tucked inside California's ADU law is a smaller cousin: the **Junior Accessory Dwelling Unit**, or JADU.\n\n  ## What defines a JADU\n\n  - **Maximum 500 sq ft**\n  - Must be carved out of the existing primary home's footprint (not a new structure)\n  - Can share a bathroom with the primary home (unique to JADUs)\n  - Must have its own kitchen and entrance\n\n  ## When a JADU makes sense\n\n  For homeowners who want to add a small rental or a private suite for a college-age kid without building a separate structure. Common conversions: master suite + attached bath becomes JADU; remaining house keeps the rest.\n\n  ## When a regular ADU makes more sense\n\n  Almost any other case. JADUs are constrained, share infrastructure, and don't add nearly as much resale value as a detached ADU.\n\n  > HEMMA doesn't currently sell JADU conversions — they're highly site-specific renovations rather than a productized build. But we'll happily refer you to a local contractor if a JADU is the right fit.",
    category: "regulations",
    heroImageUrl: "/blog-images/af8596de-d3c1-4408-b4c3-cda4cb011383",
    isPublished: true,
    publishedAt: new Date("2026-04-23T02:50:52.961"),
    createdAt: new Date("2026-05-03T03:11:43.494401"),
    updatedAt: new Date("2026-05-03T03:11:43.494401"),
  },
  {
    id: 12,
    slug: "the-midcentury-design-language",
    title: "The midcentury design language behind every floor plan.",
    excerpt: "Palm Springs, the Case Study Houses, post-and-beam warmth. What midcentury modern actually means as a design brief — and how it shows up in your ADU.",
    body: "\"Midcentury modern\" is one of those phrases that means everything and nothing. It sells kitchenware, tile patterns, and furniture that would have looked nothing like the actual buildings it claims to reference. So let's be specific.\n\n  ## What we mean by midcentury modern\n\n  The movement peaked in California between roughly 1945 and 1970. Its buildings share a handful of actual principles:\n\n  1. **Post-and-beam structure, expressed.** The bones show. Beams are not hidden behind drywall. Columns are not wrapped in finish. The structure is the aesthetic.\n\n  2. **The indoor-outdoor threshold.** Original midcentury houses were obsessed with erasing the line between inside and outside. Glass walls, sliding doors, overhanging rooflines that shelter a patio the same way the roof shelters the interior.\n\n  3. **Warm materials, cool geometry.** Walnut, cedar, concrete, steel. Not a lot of softening. The warmth comes from the wood grain, not from decoration.\n\n  4. **Flat planes over pitched roofs.** Or, when pitched, pitched deliberately — the shed roof, the butterfly, the cantilevered overhang. The roof as a sculptural element.\n\n  ## Where you see it in our floor plans\n\n  The **shed roof** on every plan pitches from low eave to high ridge, directing your eye toward the high-glazed wall. The **exposed rafters** inside continue the exterior beam language. The **sliding glass door** occupies the full wall of the primary living space.\n\n  These aren't stylistic choices bolted onto a conventional structure. They're the structure.\n\n  ## Palm Springs vs. the whole state\n\n  Palm Springs is the brand ambassador for midcentury modern — the Kaufmann House, Neutra's desert work, the Biltmore. But the idiom was never limited to desert modernism. The **Eichler tracts** of Palo Alto and San Jose brought post-and-beam to the middle class. The **Case Study Houses** proved you could build this way for a fraction of the cost of custom architecture.\n\n  We're building in that tradition. California backyards, California sun angles, California materials.\n\n  > The point of a design language is that it resolves decisions before you have to make them. We know what the window frame is going to be. We know what the cabinet hardware is going to be. That clarity is what gives even a small ADU a sense of intentionality.",
    category: "inside-midcentury-adu",
    heroImageUrl: "/blog-images/942b443d-6921-473a-9cb0-2b6924105f28",
    isPublished: true,
    publishedAt: new Date("2026-04-22T02:50:52.961"),
    createdAt: new Date("2026-05-03T03:11:43.494401"),
    updatedAt: new Date("2026-05-05T20:57:51.463247"),
  },
  {
    id: 13,
    slug: "why-we-chose-walnut-over-oak",
    title: "Why we chose walnut over oak — and cedar over fiber cement.",
    excerpt: "Material choices in an ADU aren't just aesthetic. Here's why Midcentury ADU defaults to warm woods, raw concrete, and steel rather than cheaper alternatives.",
    body: "Every material in a Midcentury ADU can be explained without invoking taste. There's a functional logic to each of the defaults, and an honest accounting of what we gave up to get there.\n\n  ## Walnut, not oak\n\n  Oak is the correct default for most residential construction right now. It's abundant, stable, finishes beautifully, and comes in dozens of variations.\n\n  We use walnut in cabinets, floating shelves, and accent millwork for one reason: **it earns its cost over time.**\n\n  Walnut's dark, tight grain ages better in a rental or high-use setting. Scratches, heat exposure, ten years of coffee mugs — walnut's darkness hides minor damage in a way that lighter woods don't. In the ADU context specifically, where the unit is often tenanted or heavily used, that matters more than the upfront aesthetic case.\n\n  ## Cedar, not fiber cement\n\n  Fiber cement siding is a reasonable product. It's durable, low-maintenance, and cost-effective. It also reads as a product — there's a flatness to the texture and a uniformity to the surface that codes as manufactured rather than chosen.\n\n  We use vertical cedar cladding as the standard exterior because:\n\n  - **It ages intentionally.** Untreated cedar silvers to a warm gray over five to ten years. The building develops character rather than accumulating wear.\n  - **It belongs in California.** Cedar has a long history in California residential construction. It reads as specific to place rather than sourced from a national building products catalog.\n  - **The shadow lines work.** Vertical board-and-batten creates strong shadow lines that emphasize the structural height of the walls. It makes a one-story building look deliberate.\n\n  ## Concrete, not quartz\n\n  The countertop default is poured concrete, not quartz, not ceramic. Reasons:\n\n  1. **It's honest about what it is.** There's no simulation involved. Concrete countertops are concrete.\n  2. **They're poured in place**, which means they're exactly the right size for the countertop — no seams, no grout lines.\n  3. **They patina.** The surface changes with use. Most homeowners either embrace this or choose the quartz upgrade. The ones who embrace it rarely look back.\n\n  ## Steel, not brass or matte black\n\n  Hardware is small. It's also the most-touched surface in the house. We use brushed steel — not brass, not matte black, not chrome — because it's genuinely neutral over time. Brass trends. Matte black shows fingerprints. Brushed steel looks like itself for twenty years.\n\n  > The through-line is the same across every material choice: we want things that reward attention rather than demanding it.",
    category: "inside-midcentury-adu",
    heroImageUrl: "/blog-images/ac3dd8c2-41e0-43fa-a578-643d33d268f6",
    isPublished: true,
    publishedAt: new Date("2026-04-21T02:50:52.961"),
    createdAt: new Date("2026-05-03T03:11:43.494401"),
    updatedAt: new Date("2026-05-05T20:57:56.004441"),
  }
] as const;
  